/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import {HTMLStencilElement, JSXBase} from '@stencil/core/internal'
import {ButtonType} from './components/types'
import {Variants} from './components/vr360-button/vr360-button'
export namespace Components {
  interface Vr360Button {
    /**
     * Sets the autofocus for this element.
     */
    autoFocus?: boolean
    /**
     * Makes the button text and container slightly smaller.
     */
    dense: boolean
    /**
     * Disables this element.
     */
    disabled?: boolean
    /**
     * The form id this element origins to.
     */
    form?: string
    /**
     * Shows an infinite loading spinner and prevents further clicks.
     */
    loading?: boolean
    /**
     * The name of the element.
     */
    name?: string
    /**
     * The type of this form.  Can either be `button`, `submit` or `reset`.
     */
    type?: ButtonType
    /**
     * The button variant.  * **filled**: Contain actions that are important for your application. * **outlined**: Buttons with medium highlighting. They contain actions that are important but are not the main action in an app. * **text**: Typically used for less prominent actions, including those in dialogs and cards.
     */
    variant: Variants
  }
}
declare global {
  interface HTMLVr360ButtonElement extends Components.Vr360Button, HTMLStencilElement {}
  var HTMLVr360ButtonElement: {
    prototype: HTMLVr360ButtonElement
    new (): HTMLVr360ButtonElement
  }
  interface HTMLElementTagNameMap {
    'vr360-button': HTMLVr360ButtonElement
  }
}
declare namespace LocalJSX {
  interface Vr360Button {
    /**
     * Sets the autofocus for this element.
     */
    autoFocus?: boolean
    /**
     * Makes the button text and container slightly smaller.
     */
    dense?: boolean
    /**
     * Disables this element.
     */
    disabled?: boolean
    /**
     * The form id this element origins to.
     */
    form?: string
    /**
     * Shows an infinite loading spinner and prevents further clicks.
     */
    loading?: boolean
    /**
     * The name of the element.
     */
    name?: string
    /**
     * The type of this form.  Can either be `button`, `submit` or `reset`.
     */
    type?: ButtonType
    /**
     * The button variant.  * **filled**: Contain actions that are important for your application. * **outlined**: Buttons with medium highlighting. They contain actions that are important but are not the main action in an app. * **text**: Typically used for less prominent actions, including those in dialogs and cards.
     */
    variant?: Variants
  }
  interface IntrinsicElements {
    'vr360-button': Vr360Button
  }
}
export {LocalJSX as JSX}
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'vr360-button': LocalJSX.Vr360Button & JSXBase.HTMLAttributes<HTMLVr360ButtonElement>
    }
  }
}
